name: zeta_aztec_editor_example
description: "Demonstrates how to use the zeta_aztec_editor plugin."
publish_to: 'none'
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  zeta_aztec_editor:
    path: ../
  cupertino_icons: ^1.0.8
  flutter_widget_from_html: ^0.16.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
