name: zeta_aztec_editor
description: "Flutter plugin that bridges to native Aztec editors on iOS and Android."
version: 0.0.2

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^24.2.1

flutter:
  plugin:
    platforms:
      android:
        package: com.zebradevs.aztec.editor
        pluginClass: ZetaAztecEditorPlugin
      ios:
        pluginClass: ZetaAztecEditorPlugin