// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zebradevs.aztec

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ToolbarOptions(val raw: Int) {
  BOLD(0),
  ITALIC(1),
  UNDERLINE(2),
  STRIKE_THROUGH(3),
  HEADING1(4),
  HEADING2(5),
  HEADING3(6),
  HEADING4(7),
  HEADING5(8),
  HEADING6(9),
  ORDERED_LIST(10),
  UNORDERED_LIST(11),
  BLOCK_QUOTE(12),
  ALIGN_LEFT(13),
  ALIGN_CENTER(14),
  ALIGN_RIGHT(15),
  ALIGN_JUSTIFY(16),
  TEXT_COLOR(17),
  BACKGROUND_COLOR(18),
  LINK(19),
  IMAGE(20),
  VIDEO(21),
  HORIZONTAL_RULE(22),
  REMOVE_FORMAT(23);

  companion object {
    fun ofRaw(raw: Int): ToolbarOptions? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class Theme(val raw: Int) {
  LIGHT(0),
  DARK(1),
  SYSTEM(2);

  companion object {
    fun ofRaw(raw: Int): Theme? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EditorConfig (
  val primaryColor: String? = null,
  val backgroundColor: String? = null,
  val textColor: String? = null,
  val fileExtensions: List<String>? = null,
  val toolbarOptions: List<ToolbarOptions>? = null,
  val title: String,
  val theme: Theme
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EditorConfig {
      val primaryColor = pigeonVar_list[0] as String?
      val backgroundColor = pigeonVar_list[1] as String?
      val textColor = pigeonVar_list[2] as String?
      val fileExtensions = pigeonVar_list[3] as List<String>?
      val toolbarOptions = pigeonVar_list[4] as List<ToolbarOptions>?
      val title = pigeonVar_list[5] as String
      val theme = pigeonVar_list[6] as Theme
      return EditorConfig(primaryColor, backgroundColor, textColor, fileExtensions, toolbarOptions, title, theme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primaryColor,
      backgroundColor,
      textColor,
      fileExtensions,
      toolbarOptions,
      title,
      theme,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ToolbarOptions.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Theme.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EditorConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ToolbarOptions -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is Theme -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is EditorConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AztecEditorApi {
  fun launch(initialHtml: String?, config: EditorConfig, callback: (Result<String?>) -> Unit)

  companion object {
    /** The codec used by AztecEditorApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AztecEditorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AztecEditorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zeta_aztec_editor.AztecEditorApi.launch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val initialHtmlArg = args[0] as String?
            val configArg = args[1] as EditorConfig
            api.launch(initialHtmlArg, configArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AztecFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AztecFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onFileSelected(filePathArg: String, callback: (Result<String>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.zeta_aztec_editor.AztecFlutterApi.onFileSelected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(filePathArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as String
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
